<?php
/**
* @file
* Módulo Nodes Forcontu
* Este módulo añadirá el campo Body al tipo de contenido Mi producto
**/

/**
 * Implements hook_install().
 */
function nodes_forcontu_install() {
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['myproduct'], 'Description');
}

/**
 * Implements hook_uninstall().
 */
function nodes_forcontu_uninstall() {
}

/**
 * Implements hook_schema().
 */
function nodes_forcontu_schema() {
  $schema['nodes_forcontu'] = array(
    'description' => 'Almacena los datos del tipo de contenido Mi producto',
    'fields' => array(
      'nid' => array(
        'description' => 'Primary key nid',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'price' => array(
        'description' => 'Precio del producto',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'weight' => array(
        'description' => 'Peso del producto',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'length' => array(
        'description' => 'Longitud del producto',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'width' => array(
        'description' => 'Anchura del producto',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'height' => array(
        'description' => 'Altura del producto',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('nid'),
  );
  return $schema;
}